### ISSUE TITLE
the code is not updated in swift 2

### ISSUE THREAD

**Issue by francisadelante** [SzabZappDesigntemplates/ZDT-ExpandingCircle-Swift#1]
this is great and smart way of presenting the next view after calling some services(api) but i can't seem to convert it in swift2. Could you help me?

**Comment by szabDev** [comment]
Sure, please pull from Master again. I pushed the corrected version. :)

**Comment by szabolcssztanyi** [comment]
Sure, please pull from Master again. I pushed the corrected version. :)
